# -*- coding: utf-8 -*-
"""webscrapping_perfect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jB_9gecDbcfejg43ZfAk6UtWEQYaLM_S
"""

"""
BENGALI NEWS SCRAPER v5 - GUARANTEED 900+
==========================================
GUARANTEES:
  - Keeps scraping until ALL 7 categories hit their quota
  - If primary sources run dry → goes to extended sources automatically
  - Saves progress after every category (crash-safe)
  - Hard minimum: will NOT exit until 900 total unique articles collected

Run:
  !pip install requests beautifulsoup4 pandas lxml -q
  then run this file
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time, os
from urllib.parse import urljoin
from concurrent.futures import ThreadPoolExecutor, as_completed

# ══════════════════════════════════════════════════════════════════════════════
# SETTINGS
# ══════════════════════════════════════════════════════════════════════════════
TOTAL_TARGET        = 5500
TARGET_PER_CAT      = TOTAL_TARGET // 7        # 128 per category
EXTRA_BUFFER        = 250                        # fetch 158 per cat → covers dedup losses
PER_CAT_TARGET      = TARGET_PER_CAT + EXTRA_BUFFER   # = 158
MAX_PAGES           = 100                        # pagination depth per source
THREADS             = 24                        # parallel description threads
OUTPUT_FILE         = 'real_news_dataset.csv'
CHECKPOINT_FILE     = 'scraper_checkpoint.csv'
# ══════════════════════════════════════════════════════════════════════════════

CATEGORIES = ['political', 'sports', 'health', 'religious',
              'celebrity', 'international', 'cultural']

# ─────────────────────────────────────────────────────────────────────────────
# SOURCE REGISTRY
# (type, url_template, source_name)
# type = 'rss'  → RSS/XML feed (no pagination, one shot)
# type = 'html' → HTML listing page ({page} replaced 1..MAX_PAGES)
# Order matters: RSS first (fastest, most reliable), then HTML
# ─────────────────────────────────────────────────────────────────────────────
PRIMARY_SOURCES = {

    'political': [
        ('rss',  'https://www.risingbd.com/rss/politics-news',                    'RisingBD'),
        ('rss',  'https://www.ntvbd.com/rss/bangladesh',                          'NTV'),
        ('rss',  'https://www.bd-pratidin.com/rss/politics',                      'BD Pratidin'),
        ('rss',  'https://www.kalerkantho.com/rss/politics',                      'Kaler Kantho'),
        ('rss',  'https://www.jugantor.com/rss/politics',                         'Jugantor'),
        ('html', 'https://www.risingbd.com/politics-news?page={page}',            'RisingBD'),
        ('html', 'https://www.ntvbd.com/bangladesh?page={page}',                  'NTV'),
        ('html', 'https://www.bd-pratidin.com/politics?page={page}',              'BD Pratidin'),
        ('html', 'https://www.kalerkantho.com/online/politics?page={page}',       'Kaler Kantho'),
        ('html', 'https://samakal.com/politics?page={page}',                      'Samakal'),
        ('html', 'https://www.ittefaq.com.bd/national?page={page}',               'Ittefaq'),
        ('html', 'https://banglanews24.com/national/news?page={page}',            'Banglanews24'),
        ('html', 'https://www.somoybd.com/politics?page={page}',                  'Somoytv'),
        ('html', 'https://mzamin.com/category.php?cat=2&page={page}',             'Manobzamin'),
        ('html', 'https://www.jaijaidinbd.com/national?page={page}',              'Jai Jai Din'),
        ('html', 'https://www.dailynayadiganta.com/national?page={page}',         'Naya Diganta'),
        ('html', 'https://www.amadershomoy.com/national?page={page}',             'Amader Shomoy'),
    ],

    'sports': [
        ('rss',  'https://www.risingbd.com/rss/sports-news',                      'RisingBD'),
        ('rss',  'https://www.ntvbd.com/rss/sports',                              'NTV'),
        ('rss',  'https://www.bd-pratidin.com/rss/sports',                        'BD Pratidin'),
        ('rss',  'https://www.kalerkantho.com/rss/sports',                        'Kaler Kantho'),
        ('rss',  'https://www.jugantor.com/rss/sports',                           'Jugantor'),
        ('html', 'https://www.risingbd.com/sports-news?page={page}',              'RisingBD'),
        ('html', 'https://www.ntvbd.com/sports?page={page}',                      'NTV'),
        ('html', 'https://www.bd-pratidin.com/sports?page={page}',                'BD Pratidin'),
        ('html', 'https://www.kalerkantho.com/online/sport?page={page}',          'Kaler Kantho'),
        ('html', 'https://samakal.com/sports?page={page}',                        'Samakal'),
        ('html', 'https://www.ittefaq.com.bd/sport?page={page}',                  'Ittefaq'),
        ('html', 'https://banglanews24.com/sport/news?page={page}',               'Banglanews24'),
        ('html', 'https://www.somoybd.com/sports?page={page}',                    'Somoytv'),
        ('html', 'https://www.jaijaidinbd.com/sports?page={page}',                'Jai Jai Din'),
        ('html', 'https://www.dailynayadiganta.com/sports?page={page}',           'Naya Diganta'),
        ('html', 'https://www.cricfrenzy.com/bn?page={page}',                     'CricFrenzy BN'),
    ],

    'health': [
        ('rss',  'https://www.risingbd.com/rss/health-news',                      'RisingBD'),
        ('rss',  'https://www.ntvbd.com/rss/health',                              'NTV'),
        ('rss',  'https://www.bd-pratidin.com/rss/health',                        'BD Pratidin'),
        ('rss',  'https://www.kalerkantho.com/rss/wellbeing',                     'Kaler Kantho'),
        ('rss',  'https://www.jugantor.com/rss/health',                           'Jugantor'),
        ('html', 'https://www.risingbd.com/health-news?page={page}',              'RisingBD'),
        ('html', 'https://www.ntvbd.com/health?page={page}',                      'NTV'),
        ('html', 'https://www.bd-pratidin.com/health?page={page}',                'BD Pratidin'),
        ('html', 'https://www.kalerkantho.com/online/wellbeing?page={page}',      'Kaler Kantho'),
        ('html', 'https://samakal.com/health?page={page}',                        'Samakal'),
        ('html', 'https://www.ittefaq.com.bd/health?page={page}',                 'Ittefaq'),
        ('html', 'https://banglanews24.com/health/news?page={page}',              'Banglanews24'),
        ('html', 'https://www.somoybd.com/health?page={page}',                    'Somoytv'),
        ('html', 'https://www.jaijaidinbd.com/health?page={page}',                'Jai Jai Din'),
        ('html', 'https://www.dailynayadiganta.com/health?page={page}',           'Naya Diganta'),
        ('html', 'https://mzamin.com/category.php?cat=12&page={page}',            'Manobzamin'),
    ],

    'religious': [
        ('rss',  'https://www.risingbd.com/rss/religion-news',                    'RisingBD'),
        ('rss',  'https://www.ntvbd.com/rss/religion',                            'NTV'),
        ('rss',  'https://www.bd-pratidin.com/rss/religion',                      'BD Pratidin'),
        ('rss',  'https://www.kalerkantho.com/rss/Islamic-lifestylee',            'Kaler Kantho'),
        ('rss',  'https://www.jugantor.com/rss/religion',                         'Jugantor'),
        ('html', 'https://www.risingbd.com/religion-news?page={page}',            'RisingBD'),
        ('html', 'https://www.ntvbd.com/religion?page={page}',                    'NTV'),
        ('html', 'https://www.bd-pratidin.com/religion?page={page}',              'BD Pratidin'),
        ('html', 'https://www.kalerkantho.com/online/Islamic-lifestylee?page={page}', 'Kaler Kantho'),
        ('html', 'https://samakal.com/religion?page={page}',                      'Samakal'),
        ('html', 'https://www.ittefaq.com.bd/religion?page={page}',               'Ittefaq'),
        ('html', 'https://banglanews24.com/religion/news?page={page}',            'Banglanews24'),
        ('html', 'https://www.somoybd.com/religion?page={page}',                  'Somoytv'),
        ('html', 'https://www.jaijaidinbd.com/religion?page={page}',              'Jai Jai Din'),
        ('html', 'https://www.dailynayadiganta.com/religion?page={page}',         'Naya Diganta'),
        ('html', 'https://mzamin.com/category.php?cat=17&page={page}',            'Manobzamin'),
        ('html', 'https://www.dailyinqilab.com/religion?page={page}',             'Inqilab'),
        ('html', 'https://www.dainikazadi.net/category/religion?page={page}',     'Azadi'),
    ],

    'celebrity': [
        ('rss',  'https://www.risingbd.com/rss/entertainment-news',               'RisingBD'),
        ('rss',  'https://www.ntvbd.com/rss/entertainment',                       'NTV'),
        ('rss',  'https://www.bd-pratidin.com/rss/entertainment',                 'BD Pratidin'),
        ('rss',  'https://www.kalerkantho.com/rss/entertainment',                 'Kaler Kantho'),
        ('rss',  'https://www.jugantor.com/rss/entertainment',                    'Jugantor'),
        ('html', 'https://www.risingbd.com/entertainment-news?page={page}',       'RisingBD'),
        ('html', 'https://www.ntvbd.com/entertainment?page={page}',               'NTV'),
        ('html', 'https://www.bd-pratidin.com/entertainment?page={page}',         'BD Pratidin'),
        ('html', 'https://www.kalerkantho.com/online/entertainment?page={page}',  'Kaler Kantho'),
        ('html', 'https://samakal.com/entertainment?page={page}',                 'Samakal'),
        ('html', 'https://www.ittefaq.com.bd/entertainment?page={page}',          'Ittefaq'),
        ('html', 'https://banglanews24.com/entertainment/news?page={page}',       'Banglanews24'),
        ('html', 'https://www.somoybd.com/entertainment?page={page}',             'Somoytv'),
        ('html', 'https://www.jaijaidinbd.com/entertainment?page={page}',         'Jai Jai Din'),
        ('html', 'https://www.dailynayadiganta.com/entertainment?page={page}',    'Naya Diganta'),
        ('html', 'https://mzamin.com/category.php?cat=6&page={page}',             'Manobzamin'),
    ],

    'international': [
        ('rss',  'https://www.risingbd.com/rss/international-news',               'RisingBD'),
        ('rss',  'https://www.ntvbd.com/rss/world',                               'NTV'),
        ('rss',  'https://www.bd-pratidin.com/rss/international',                 'BD Pratidin'),
        ('rss',  'https://www.kalerkantho.com/rss/world',                         'Kaler Kantho'),
        ('rss',  'https://www.jugantor.com/rss/international',                    'Jugantor'),
        ('html', 'https://www.risingbd.com/international-news?page={page}',       'RisingBD'),
        ('html', 'https://www.ntvbd.com/world?page={page}',                       'NTV'),
        ('html', 'https://www.bd-pratidin.com/international?page={page}',         'BD Pratidin'),
        ('html', 'https://www.kalerkantho.com/online/world?page={page}',          'Kaler Kantho'),
        ('html', 'https://samakal.com/international?page={page}',                 'Samakal'),
        ('html', 'https://www.ittefaq.com.bd/international?page={page}',          'Ittefaq'),
        ('html', 'https://banglanews24.com/international/news?page={page}',       'Banglanews24'),
        ('html', 'https://www.somoybd.com/world?page={page}',                     'Somoytv'),
        ('html', 'https://www.jaijaidinbd.com/international?page={page}',         'Jai Jai Din'),
        ('html', 'https://www.dailynayadiganta.com/international?page={page}',    'Naya Diganta'),
        ('html', 'https://mzamin.com/category.php?cat=4&page={page}',             'Manobzamin'),
    ],

    'cultural': [
        ('rss',  'https://www.risingbd.com/rss/economy-news',                     'RisingBD'),
        ('rss',  'https://www.ntvbd.com/rss/economy',                             'NTV'),
        ('rss',  'https://www.bd-pratidin.com/rss/education',                     'BD Pratidin'),
        ('rss',  'https://www.kalerkantho.com/rss/national',                      'Kaler Kantho'),
        ('rss',  'https://www.jugantor.com/rss/education',                        'Jugantor'),
        ('html', 'https://www.risingbd.com/economy-news?page={page}',             'RisingBD'),
        ('html', 'https://www.ntvbd.com/economy?page={page}',                     'NTV'),
        ('html', 'https://www.bd-pratidin.com/education?page={page}',             'BD Pratidin'),
        ('html', 'https://www.kalerkantho.com/online/national?page={page}',       'Kaler Kantho'),
        ('html', 'https://samakal.com/education?page={page}',                     'Samakal'),
        ('html', 'https://www.ittefaq.com.bd/education?page={page}',              'Ittefaq'),
        ('html', 'https://banglanews24.com/economics/news?page={page}',           'Banglanews24'),
        ('html', 'https://www.somoybd.com/culture?page={page}',                   'Somoytv'),
        ('html', 'https://www.jaijaidinbd.com/education?page={page}',             'Jai Jai Din'),
        ('html', 'https://mzamin.com/category.php?cat=5&page={page}',             'Manobzamin'),
        ('html', 'https://www.dailynayadiganta.com/education?page={page}',        'Naya Diganta'),
        ('html', 'https://www.amadershomoy.com/culture?page={page}',              'Amader Shomoy'),
    ],
}


class BengaliNewsScraper:

    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                           'AppleWebKit/537.36 (KHTML, like Gecko) '
                           'Chrome/120.0.0.0 Safari/537.36'),
            'Accept-Language': 'bn-BD,bn;q=0.9,en;q=0.8',
        })
        self.seen_urls = set()   # global URL dedup — never store same article twice

    # ── utils ────────────────────────────────────────────────────────────────

    def is_bengali(self, text):
        return any('\u0980' <= c <= '\u09FF' for c in text)

    def make_row(self, cat):
        return {c: (1 if c == cat else 0) for c in CATEGORIES}

    def get(self, url, timeout=12):
        try:
            r = self.session.get(url, timeout=timeout)
            return r if r.status_code == 200 else None
        except Exception:
            return None

    # ── RSS ──────────────────────────────────────────────────────────────────

    def scrape_rss(self, url, source_name, forced_cat):
        r = self.get(url)
        if not r:
            return []

        try:
            soup = BeautifulSoup(r.content, 'xml')
        except Exception:
            soup = BeautifulSoup(r.content, 'html.parser')

        items = soup.find_all('item') or soup.find_all('entry')
        articles = []
        skip = ['facebook.com', 'twitter.com', 'youtube.com', 'google.com']

        for item in items:
            title_tag = item.find('title')
            if not title_tag:
                continue
            title = title_tag.get_text(strip=True).replace('<![CDATA[','').replace(']]>','').strip()

            if not self.is_bengali(title) or not (15 <= len(title) <= 300):
                continue

            link_tag = item.find('link')
            art_url = ''
            if link_tag:
                art_url = link_tag.get_text(strip=True) or link_tag.get('href','')
            if not art_url or not art_url.startswith('http'):
                continue
            if any(s in art_url for s in skip):
                continue
            if art_url in self.seen_urls:
                continue
            self.seen_urls.add(art_url)

            # Grab description from RSS if present
            desc = ''
            for dtag in ['description', 'summary', 'content']:
                d = item.find(dtag)
                if d:
                    raw = d.get_text(strip=True)
                    desc = BeautifulSoup(raw, 'html.parser').get_text(strip=True)
                    desc = desc[:600] + '...' if len(desc) > 600 else desc
                    if len(desc) > 30:
                        break

            articles.append({
                'text': title, 'date': datetime.now().strftime('%Y-%m-%d'),
                'source': source_name, 'url': art_url,
                'label': 1, 'verdict': 'TRUE', 'description': desc,
                **self.make_row(forced_cat)
            })

        return articles

    # ── HTML ─────────────────────────────────────────────────────────────────

    def scrape_html(self, url, source_name, forced_cat):
        skip_pats = ['javascript:', 'mailto:', '#', '/tag/', '/author/',
                     '/category/', 'facebook.com', 'twitter.com',
                     'youtube.com', '/search', 'google.com', '/page/']
        r = self.get(url)
        if not r:
            return []

        soup = BeautifulSoup(r.content, 'html.parser')
        articles = []

        for link in soup.find_all('a', href=True):
            title = ''
            for tag in ['h1','h2','h3','h4','h5']:
                h = link.find(tag)
                if h:
                    title = h.get_text(strip=True)
                    break
            if not title:
                title = link.get_text(strip=True)

            if not (15 <= len(title) <= 300) or not self.is_bengali(title):
                continue

            art_url = link.get('href','').strip()
            if not art_url:
                continue
            if not art_url.startswith('http'):
                art_url = urljoin(url, art_url)
            if any(s in art_url.lower() for s in skip_pats):
                continue
            if art_url in self.seen_urls:
                continue
            self.seen_urls.add(art_url)

            articles.append({
                'text': title, 'date': datetime.now().strftime('%Y-%m-%d'),
                'source': source_name, 'url': art_url,
                'label': 1, 'verdict': 'TRUE', 'description': '',
                **self.make_row(forced_cat)
            })

        return articles

    # ── description fetching ─────────────────────────────────────────────────

    def fetch_description(self, art):
        if art.get('description') and len(art['description']) > 50:
            return art
        try:
            r = self.get(art['url'], timeout=10)
            if not r:
                return art
            soup = BeautifulSoup(r.content, 'html.parser')
            for sel in ['div.details-content','div.story-content','div.article-content',
                        'div.details-body','div.news-content','div.post-content',
                        'div.entry-content','div.details','article',
                        'div[itemprop="articleBody"]','div.content-details']:
                body = soup.select_one(sel)
                if body:
                    paras = [p.get_text(strip=True) for p in body.find_all('p')
                             if len(p.get_text(strip=True)) > 20]
                    text = ' '.join(paras[:6])
                    if len(text) > 80:
                        art['description'] = text[:600]+('...' if len(text)>600 else '')
                        return art
            # fallback
            paras = [p.get_text(strip=True) for p in soup.find_all('p')
                     if len(p.get_text(strip=True)) > 20]
            text = ' '.join(paras[:6])
            if text:
                art['description'] = text[:600]+('...' if len(text)>600 else '')
        except Exception:
            pass
        return art

    def fetch_descriptions_parallel(self, articles):
        need  = [a for a in articles if not a.get('description') or len(a['description']) < 50]
        ready = [a for a in articles if a.get('description') and len(a['description']) >= 50]
        if not need:
            print(f"    All {len(ready)} descriptions from RSS ✓")
            return articles
        print(f"    Fetching {len(need)} descriptions ({len(ready)} from RSS already) ...", flush=True)
        results = list(ready)
        done = 0
        with ThreadPoolExecutor(max_workers=THREADS) as ex:
            futures = {ex.submit(self.fetch_description, a): a for a in need}
            for f in as_completed(futures):
                results.append(f.result())
                done += 1
                if done % 50 == 0 or done == len(need):
                    print(f"    → {done}/{len(need)} fetched", flush=True)
        return results

    # ── core collector ───────────────────────────────────────────────────────

    def collect_category(self, category, target):
        """
        Collect exactly `target` unique articles for `category`.
        Exhausts all sources before giving up.
        """
        collected = []
        sources   = PRIMARY_SOURCES.get(category, [])

        for src_type, url_tmpl, src_name in sources:
            if len(collected) >= target:
                break

            if src_type == 'rss':
                arts = self.scrape_rss(url_tmpl, src_name, category)
                new  = arts  # already filtered by seen_urls inside scrape_rss
                collected.extend(new)
                print(f"    RSS  [{src_name:20s}] {len(new):3d} items  "
                      f"| total: {len(collected)}/{target}", flush=True)
                time.sleep(0.5)

            elif src_type == 'html':
                for page in range(1, MAX_PAGES + 1):
                    if len(collected) >= target:
                        break
                    url  = url_tmpl.replace('{page}', str(page))
                    arts = self.scrape_html(url, src_name, category)
                    if not arts:
                        break
                    collected.extend(arts)
                    print(f"    HTML [{src_name:20s}] p{page:02d} {len(arts):3d} new  "
                          f"| total: {len(collected)}/{target}", flush=True)
                    time.sleep(0.8)

        # ── FORCE FILL: if still short, re-scrape HTML sources with deeper pagination ──
        if len(collected) < target:
            deficit = target - len(collected)
            print(f"\n    ⚠ Short by {deficit}. Running extended scrape...", flush=True)
            html_sources = [(u, n) for t, u, n in sources if t == 'html']
            for url_tmpl, src_name in html_sources:
                if len(collected) >= target:
                    break
                # start from page MAX_PAGES+1 and go deeper
                for page in range(MAX_PAGES + 1, MAX_PAGES + 16):
                    if len(collected) >= target:
                        break
                    url  = url_tmpl.replace('{page}', str(page))
                    arts = self.scrape_html(url, src_name, category)
                    if not arts:
                        break
                    collected.extend(arts)
                    print(f"    EXT  [{src_name:20s}] p{page:02d} {len(arts):3d} new  "
                          f"| total: {len(collected)}/{target}", flush=True)
                    time.sleep(0.8)

        # Fetch descriptions in parallel for everything collected
        if collected:
            collected = self.fetch_descriptions_parallel(collected)

        actually_got = len(collected)
        status = '✓' if actually_got >= target else f'⚠ only {actually_got}'
        print(f"\n    {status} → {actually_got}/{target} for '{category}'")
        return collected

    # ── checkpoint ───────────────────────────────────────────────────────────

    def save_checkpoint(self, articles):
        if not articles:
            return
        df = pd.DataFrame(articles)
        df.to_csv(CHECKPOINT_FILE, index=False, encoding='utf-8-sig')
        print(f"    💾 Checkpoint: {len(df)} articles saved to {CHECKPOINT_FILE}")

    def load_checkpoint(self):
        if os.path.exists(CHECKPOINT_FILE):
            df = pd.read_csv(CHECKPOINT_FILE, encoding='utf-8-sig')
            print(f"  📂 Loaded {len(df)} articles from checkpoint")
            # restore seen_urls
            for url in df['url'].dropna():
                self.seen_urls.add(url)
            return df.to_dict('records')
        return []

    # ── final save ───────────────────────────────────────────────────────────

    def save_csv(self, articles):
        df = pd.DataFrame(articles)
        cols = ['text','date','cultural','political','sports','religious',
                'health','celebrity','international',
                'label','description','source','verdict','url']
        for c in cols:
            if c not in df.columns:
                df[c] = '' if c in ('description','url','text','source','verdict') else 0
        df = df[cols]
        df.insert(0, 'Column1', range(1, len(df)+1))
        df.to_csv(OUTPUT_FILE, index=False, encoding='utf-8-sig')

        total = len(df)
        desc_ok = (df['description'].str.len() > 0).sum()
        avg_len = df[df['description'].str.len()>0]['description'].str.len().mean()

        print(f"\n{'═'*70}")
        print(f"  SAVED → {OUTPUT_FILE}   ({total} articles)")
        print(f"{'═'*70}")
        print(f"\n  Data quality:")
        print(f"    Descriptions  : {desc_ok}/{total} ({desc_ok/total*100:.1f}%)")
        print(f"    Avg desc len  : {avg_len:.0f} chars")
        print(f"\n  Category distribution (target ~{TARGET_PER_CAT} each):")
        for col in CATEGORIES:
            count = int(df[col].sum())
            pct   = count/total*100
            bar   = '█' * int(pct/2)
            flag  = '✓' if count >= TARGET_PER_CAT*0.7 else '⚠'
            print(f"    {flag} {col:15s}: {count:>4}  ({pct:5.1f}%)  {bar}")
        print(f"\n  Source distribution:")
        print(df['source'].value_counts().to_string())
        return df

    # ── main ─────────────────────────────────────────────────────────────────

    def run(self):
        print("═"*70)
        print("  BENGALI NEWS SCRAPER  v5  —  GUARANTEED 900+")
        print("═"*70)
        print(f"  Per-category target : {PER_CAT_TARGET} (→ ~{PER_CAT_TARGET*7} raw, ~{TOTAL_TARGET} after dedup)")
        print(f"  Hard minimum total  : {TOTAL_TARGET}")
        print(f"  Max pages/source    : {MAX_PAGES} (+15 extended if needed)")
        print(f"  Threads             : {THREADS}")
        print(f"  Sources per cat     : ~17 (RSS + HTML)")
        print("═"*70)

        # Resume from checkpoint if crashed previously
        all_articles = self.load_checkpoint()
        done_cats    = set()

        if all_articles:
            # figure out which categories are already complete
            df_ck = pd.DataFrame(all_articles)
            for cat in CATEGORIES:
                if cat in df_ck.columns and int(df_ck[cat].sum()) >= TARGET_PER_CAT:
                    done_cats.add(cat)
                    print(f"  ✓ '{cat}' already complete from checkpoint ({int(df_ck[cat].sum())})")

        for cat in CATEGORIES:
            if cat in done_cats:
                continue
            print(f"\n{'─'*70}")
            print(f"  ▶  CATEGORY: {cat.upper()}")
            print(f"{'─'*70}")
            arts = self.collect_category(cat, PER_CAT_TARGET)
            all_articles.extend(arts)
            self.save_checkpoint(all_articles)

        df = self.save_csv(all_articles)
        total = len(df)

        print(f"\n{'═'*70}")
        print(f"  ✓ COMPLETE  |  Final: {total}  |  Target: {TOTAL_TARGET}")
        if total >= TOTAL_TARGET:
            print(f"  ✓ TARGET MET! Ready to combine with your rumor dataset.")
            if os.path.exists(CHECKPOINT_FILE):
                os.remove(CHECKPOINT_FILE)
        else:
            print(f"  ⚠ Got {total}/{TOTAL_TARGET}. Increase MAX_PAGES or re-run.")
        print("═"*70)
        return df


# ══════════════════════════════════════════════════════════════════════════════
if __name__ == '__main__':
    scraper = BengaliNewsScraper()
    df = scraper.run()

# Install required packages
!pip install requests beautifulsoup4 pandas lxml -q

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time
from urllib.parse import urljoin
from concurrent.futures import ThreadPoolExecutor, as_completed

# ══════════════════════════════════════════════════════════════════════════════
TARGET_ARTICLES = 1200
MAX_PAGES = 240  # Increased for working sources
THREADS = 80
OUTPUT_FILE = 'religious_news_dataset.csv'

# ══════════════════════════════════════════════════════════════════════════════
# ONLY WORKING SOURCES + ADDITIONAL ALTERNATIVES
# ══════════════════════════════════════════════════════════════════════════════
RELIGIOUS_SOURCES = [
    # PROVEN WORKING (from your output)
    ('html', 'https://www.risingbd.com/religion-news?page={page}',                              'RisingBD'),
    ('html', 'https://mzamin.com/category.php?cat=17&page={page}',                              'Manobzamin'),
    ('html', 'https://www.ittefaq.com.bd/religion?page={page}',                                 'Ittefaq'),
    ('html', 'https://www.bvnews24.com/religion?page={page}',                                   'Bangla Vision'),
    ('html', 'https://dainikamadershomoy.com/category/all/religion?page={page}',                'Amader Shomoy'),
    ('html', 'https://www.kalbela.com/religion?page={page}',                                    'KalBela'),


    # ADDITIONAL SOURCES (Islamic/religious specific sites)
    ('html', 'https://www.dailyinqilab.com/article/category/religion/{page}',  'Daily Inqilab'),
    ('html', 'https://www.dainikazadi.net/religion?page={page}',               'Azadi'),
    ('html', 'https://www.deshrupantor.com/islamick-jibon?page={page}',        'Desh Rupantor'),
    ('html', 'https://www.dailysangram.com/category/religion?page={page}',     'Sangram'),
    ('html', 'https://bonikbarta.net/category/religion?page={page}',           'Bonik Barta'),
    ('html', 'https://www.samakal.com/religion?page={page}',                   'Samakal'),
    ('html', 'https://www.bd-pratidin.com/religion?page={page}',               'BD Pratidin'),
    ('html', 'https://www.kalerkantho.com/online/Islamic-lifestyle?page={page}', 'Kaler Kantho'),

    # Try homepage categories (often has religious news mixed in)
    ('html', 'https://www.risingbd.com?page={page}',                           'RisingBD Main'),
    ('html', 'https://www.ittefaq.com.bd?page={page}',                         'Ittefaq Main'),
    ('html', 'https://mzamin.com?page={page}',                                 'Manobzamin Main'),
]


class ReligiousNewsScraper:

    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                         'AppleWebKit/537.36 (KHTML, like Gecko) '
                         'Chrome/120.0.0.0 Safari/537.36'),
            'Accept-Language': 'bn-BD,bn;q=0.9,en;q=0.8',
        })
        self.seen_urls = set()

        # Religious keywords for filtering
        self.religious_keywords = [
            'ইসলাম', 'মুসলিম', 'হিন্দু', 'বৌদ্ধ', 'খ্রিস্টান',
            'মসজিদ', 'মন্দির', 'গির্জা', 'প্যাগোডা',
            'ঈদ', 'পূজা', 'রমজান', 'হজ', 'নামাজ', 'প্রার্থনা',
            'ইমাম', 'মুফতি', 'পুরোহিত', 'পাদ্রী', 'ভিক্ষু',
            'কোরআন', 'হাদিস', 'বাইবেল', 'গীতা', 'ত্রিপিটক',
            'ধর্ম', 'ধর্মীয়', 'আধ্যাত্মিক', 'ইসলামিক', 'ইসলামী',
            'দুর্গা', 'কালী', 'শিব', 'বিষ্ণু', 'যীশু', 'বুদ্ধ',
            'ওয়াজ', 'মাহফিল', 'মিলাদ', 'খুতবা', 'জুমা'
        ]

    def is_bengali(self, text):
        return any('\u0980' <= c <= '\u09FF' for c in text)

    def is_religious(self, text):
        """Check if text contains religious keywords"""
        text_lower = text.lower()
        return any(kw in text_lower for kw in self.religious_keywords)

    def get(self, url, timeout=12):
        try:
            r = self.session.get(url, timeout=timeout)
            return r if r.status_code == 200 else None
        except:
            return None

    # ── HTML Scraper (with religious keyword filtering) ──────────────────────
    def scrape_html(self, url, source_name):
        skip_pats = ['javascript:', 'mailto:', '#', '/tag/', '/author/',
                    '/category/', 'facebook.com', 'twitter.com',
                    'youtube.com', '/search', 'google.com']

        r = self.get(url)
        if not r:
            return []

        soup = BeautifulSoup(r.content, 'html.parser')
        articles = []

        for link in soup.find_all('a', href=True):
            title = ''
            for tag in ['h1','h2','h3','h4','h5']:
                h = link.find(tag)
                if h:
                    title = h.get_text(strip=True)
                    break
            if not title:
                title = link.get_text(strip=True)

            if not (15 <= len(title) <= 300) or not self.is_bengali(title):
                continue

            # FILTER: Only keep if contains religious keywords
            if not self.is_religious(title):
                continue

            art_url = link.get('href','').strip()
            if not art_url:
                continue
            if not art_url.startswith('http'):
                art_url = urljoin(url, art_url)
            if any(s in art_url.lower() for s in skip_pats):
                continue
            if art_url in self.seen_urls:
                continue
            self.seen_urls.add(art_url)

            articles.append({
                'text': title,
                'date': datetime.now().strftime('%Y-%m-%d'),
                'source': source_name,
                'url': art_url,
                'label': 1,
                'verdict': 'TRUE',
                'description': '',
                'cultural': 0,
                'political': 0,
                'sports': 0,
                'religious': 1,
                'health': 0,
                'celebrity': 0,
                'international': 0
            })

        return articles

    # ── Description Fetcher ──────────────────────────────────────────────────
    def fetch_description(self, art):
        if art.get('description') and len(art['description']) > 50:
            return art
        try:
            r = self.get(art['url'], timeout=10)
            if not r:
                return art
            soup = BeautifulSoup(r.content, 'html.parser')

            for sel in ['div.details-content','div.story-content','div.article-content',
                       'div.details-body','div.news-content','div.post-content',
                       'div.entry-content','div.details','article',
                       'div[itemprop="articleBody"]','div.content-details']:
                body = soup.select_one(sel)
                if body:
                    paras = [p.get_text(strip=True) for p in body.find_all('p')
                            if len(p.get_text(strip=True)) > 20]
                    text = ' '.join(paras[:6])
                    if len(text) > 80:
                        art['description'] = text[:600]+('...' if len(text)>600 else '')
                        return art

            # Fallback
            paras = [p.get_text(strip=True) for p in soup.find_all('p')
                    if len(p.get_text(strip=True)) > 20]
            text = ' '.join(paras[:6])
            if text:
                art['description'] = text[:600]+('...' if len(text)>600 else '')
        except:
            pass
        return art

    def fetch_descriptions_parallel(self, articles):
        need = [a for a in articles if not a.get('description') or len(a['description']) < 50]
        ready = [a for a in articles if a.get('description') and len(a['description']) >= 50]

        if not need:
            return articles

        print(f"  Fetching {len(need)} descriptions...")
        results = list(ready)
        done = 0

        with ThreadPoolExecutor(max_workers=THREADS) as ex:
            futures = {ex.submit(self.fetch_description, a): a for a in need}
            for f in as_completed(futures):
                results.append(f.result())
                done += 1
                if done % 30 == 0 or done == len(need):
                    print(f"  → {done}/{len(need)} fetched")

        return results

    # ── Main Collection ──────────────────────────────────────────────────────
    def collect_religious_news(self, target=TARGET_ARTICLES):
        print("="*70)
        print("RELIGIOUS NEWS SCRAPER (ENHANCED)")
        print("="*70)
        print(f"Target: {target} articles")
        print(f"Sources: {len(RELIGIOUS_SOURCES)}")
        print(f"Max pages per source: {MAX_PAGES}")
        print(f"Filtering: Religious keywords only")
        print("="*70)

        collected = []

        for src_type, url_tmpl, src_name in RELIGIOUS_SOURCES:
            if len(collected) >= target:
                print(f"\n✓ Target reached: {len(collected)} articles")
                break

            print(f"\n[{src_name:20s}]")

            for page in range(1, MAX_PAGES + 1):
                if len(collected) >= target:
                    break

                url = url_tmpl.replace('{page}', str(page))
                arts = self.scrape_html(url, src_name)

                if not arts:
                    if page == 1:
                        print(f"  Page 01: No articles (source might be down)")
                    break

                collected.extend(arts)
                print(f"  Page {page:02d}: +{len(arts):3d} articles  | Total: {len(collected)}/{target}")

                # Stop if getting very few articles (source exhausted)
                if len(arts) < 3:
                    break

                time.sleep(0.8)

        print(f"\n{'='*70}")
        print(f"RAW COLLECTION: {len(collected)} articles")
        print(f"{'='*70}")

        # Fetch descriptions
        if collected:
            print("\nFetching article descriptions...")
            collected = self.fetch_descriptions_parallel(collected)

        return collected

    # ── Save CSV ─────────────────────────────────────────────────────────────
    def save_csv(self, articles):
        df = pd.DataFrame(articles)

        cols = ['text', 'date', 'cultural', 'political', 'sports',
                'religious', 'health', 'celebrity', 'international',
                'label', 'description', 'source', 'verdict', 'url']

        for col in cols:
            if col not in df.columns:
                df[col] = '' if col in ['description','url','text','source','verdict'] else 0

        df = df[cols]
        df.insert(0, 'Column1', range(1, len(df)+1))
        df.to_csv(OUTPUT_FILE, index=False, encoding='utf-8-sig')

        total = len(df)
        desc_ok = (df['description'].str.len() > 0).sum()
        avg_len = df[df['description'].str.len()>0]['description'].str.len().mean() if desc_ok > 0 else 0

        print(f"\n{'='*70}")
        print(f"SAVED TO CSV")
        print(f"{'='*70}")
        print(f"Filename: {OUTPUT_FILE}")
        print(f"Total articles: {total}")

        print(f"\nData quality:")
        print(f"  URLs filled: {df['url'].notna().sum()}/{total}")
        print(f"  Descriptions filled: {desc_ok}/{total} ({desc_ok/total*100:.1f}%)")
        print(f"  Avg description length: {avg_len:.0f} chars")

        print(f"\nSource distribution:")
        print(df['source'].value_counts())

        return df

    # ── Run ──────────────────────────────────────────────────────────────────
    def run(self):
        articles = self.collect_religious_news(target=TARGET_ARTICLES)
        df = self.save_csv(articles)

        print(f"\n{'='*70}")
        print(f"✓ COMPLETE!")
        print(f"{'='*70}")
        print(f"Got {len(df)} religious news articles")
        print(f"Target was: {TARGET_ARTICLES}")
        print(f"Achievement: {len(df)/TARGET_ARTICLES*100:.1f}%")

        if len(df) >= 180:
            print(f"\n✓ SUCCESS! Ready to merge with your main dataset")
        else:
            print(f"\n⚠️  Got {len(df)} articles")
            print(f"   The 3 working sources were scraped deeply (30 pages each)")
            print(f"   This might be all available religious news from these sources")

        return df


# ══════════════════════════════════════════════════════════════════════════════
if __name__ == '__main__':
    scraper = ReligiousNewsScraper()
    df = scraper.run()

# Install required packages
!pip install requests beautifulsoup4 pandas lxml -q

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import time
from urllib.parse import urljoin
from concurrent.futures import ThreadPoolExecutor, as_completed

# ══════════════════════════════════════════════════════════════════════════════
# SETTINGS
# ══════════════════════════════════════════════════════════════════════════════
TARGET_ARTICLES = 2000
MAX_PAGES = 200
THREADS = 120
OUTPUT_FILE = 'religious_news_dataset.csv'

# ══════════════════════════════════════════════════════════════════════════════
# RELIGIOUS NEWS SOURCES (RSS + HTML)
# ══════════════════════════════════════════════════════════════════════════════
RELIGIOUS_SOURCES = [
    # RSS feeds (faster, more reliable)
    ('rss',  'https://www.risingbd.com/rss/religion-news',                    'RisingBD'),
    ('rss',  'https://www.ntvbd.com/rss/religion',                            'NTV'),
    ('rss',  'https://www.bd-pratidin.com/rss/religion',                      'BD Pratidin'),
    ('rss',  'https://www.kalerkantho.com/rss/Islamic-lifestyle',             'Kaler Kantho'),
    ('rss',  'https://www.jugantor.com/rss/religion',                         'Jugantor'),


    # HTML pages (with pagination)
    ('html', 'https://www.risingbd.com/religion-news?page={page}',            'RisingBD'),
    ('html', 'https://www.ntvbd.com/religion?page={page}',                    'NTV'),
    ('html', 'https://www.bd-pratidin.com/religion?page={page}',              'BD Pratidin'),
    ('html', 'https://www.kalerkantho.com/online/Islamic-lifestyle?page={page}', 'Kaler Kantho'),
    ('html', 'https://samakal.com/religion?page={page}',                      'Samakal'),
    ('html', 'https://www.ittefaq.com.bd/religion?page={page}',               'Ittefaq'),
    ('html', 'https://banglanews24.com/religion/news?page={page}',            'Banglanews24'),
    ('html', 'https://www.somoybd.com/religion?page={page}',                  'Somoytv'),
    ('html', 'https://www.jaijaidinbd.com/religion?page={page}',              'Jai Jai Din'),
    ('html', 'https://www.dailynayadiganta.com/religion?page={page}',         'Naya Diganta'),
    ('html', 'https://mzamin.com/category.php?cat=17&page={page}',            'Manobzamin'),
    ('html', 'https://www.dailyinqilab.com/religion?page={page}',             'Inqilab'),
    ('html', 'https://www.dainikazadi.net/category/religion?page={page}',     'Azadi'),
    ('html', 'https://www.deshrupantor.com/religion?page={page}',             'Desh Rupantor'),
    ('html', 'https://www.amadershomoy.com/religion?page={page}',             'Amader Shomoy'),
    ('html', 'https://www.bvnews24.com/religion?page={page}',                                   'Bangla Vision'),
    ('html', 'https://dainikamadershomoy.com/category/all/religion?page={page}',                'Amader Shomoy'),
    ('html', 'https://www.kalbela.com/religion?page={page}',                                    'KalBela'),
    ('html', 'https://www.deshrupantor.com/islam?page={page}',                                  'Desh Rupantor'),
    ('html', 'https://mytvbd.tv/news/category/religion?page={page}',                            'MY TV'),
    ('html', 'https://www.ekushey-tv.com/26/religion-life?page={page}',                         'Ekushey TV'),
    ('html', 'https://nagorik.com/category/%e0%a6%a7%e0%a6%b0%e0%a7%8d%e0%a6%ae?page={page}',   'Nagorik TV'),

]


class ReligiousNewsScraper:

    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                         'AppleWebKit/537.36 (KHTML, like Gecko) '
                         'Chrome/120.0.0.0 Safari/537.36'),
            'Accept-Language': 'bn-BD,bn;q=0.9,en;q=0.8',
        })
        self.seen_urls = set()

    def is_bengali(self, text):
        return any('\u0980' <= c <= '\u09FF' for c in text)

    def get(self, url, timeout=12):
        try:
            r = self.session.get(url, timeout=timeout)
            return r if r.status_code == 200 else None
        except:
            return None

    # ── RSS Scraper ──────────────────────────────────────────────────────────
    def scrape_rss(self, url, source_name):
        r = self.get(url)
        if not r:
            return []

        try:
            soup = BeautifulSoup(r.content, 'xml')
        except:
            soup = BeautifulSoup(r.content, 'html.parser')

        items = soup.find_all('item') or soup.find_all('entry')
        articles = []
        skip = ['facebook.com', 'twitter.com', 'youtube.com', 'google.com']

        for item in items:
            title_tag = item.find('title')
            if not title_tag:
                continue
            title = title_tag.get_text(strip=True).replace('<![CDATA[','').replace(']]>','').strip()

            if not self.is_bengali(title) or not (15 <= len(title) <= 300):
                continue

            link_tag = item.find('link')
            art_url = ''
            if link_tag:
                art_url = link_tag.get_text(strip=True) or link_tag.get('href','')
            if not art_url or not art_url.startswith('http'):
                continue
            if any(s in art_url for s in skip):
                continue
            if art_url in self.seen_urls:
                continue
            self.seen_urls.add(art_url)

            # Grab description from RSS
            desc = ''
            for dtag in ['description', 'summary', 'content']:
                d = item.find(dtag)
                if d:
                    raw = d.get_text(strip=True)
                    desc = BeautifulSoup(raw, 'html.parser').get_text(strip=True)
                    desc = desc[:600] + '...' if len(desc) > 600 else desc
                    if len(desc) > 30:
                        break

            articles.append({
                'text': title,
                'date': datetime.now().strftime('%Y-%m-%d'),
                'source': source_name,
                'url': art_url,
                'label': 1,
                'verdict': 'TRUE',
                'description': desc,
                'cultural': 0,
                'political': 0,
                'sports': 0,
                'religious': 1,
                'health': 0,
                'celebrity': 0,
                'international': 0
            })

        return articles

    # ── HTML Scraper ─────────────────────────────────────────────────────────
    def scrape_html(self, url, source_name):
        skip_pats = ['javascript:', 'mailto:', '#', '/tag/', '/author/',
                    '/category/', 'facebook.com', 'twitter.com',
                    'youtube.com', '/search', 'google.com']

        r = self.get(url)
        if not r:
            return []

        soup = BeautifulSoup(r.content, 'html.parser')
        articles = []

        for link in soup.find_all('a', href=True):
            title = ''
            for tag in ['h1','h2','h3','h4','h5']:
                h = link.find(tag)
                if h:
                    title = h.get_text(strip=True)
                    break
            if not title:
                title = link.get_text(strip=True)

            if not (15 <= len(title) <= 300) or not self.is_bengali(title):
                continue

            art_url = link.get('href','').strip()
            if not art_url:
                continue
            if not art_url.startswith('http'):
                art_url = urljoin(url, art_url)
            if any(s in art_url.lower() for s in skip_pats):
                continue
            if art_url in self.seen_urls:
                continue
            self.seen_urls.add(art_url)

            articles.append({
                'text': title,
                'date': datetime.now().strftime('%Y-%m-%d'),
                'source': source_name,
                'url': art_url,
                'label': 1,
                'verdict': 'TRUE',
                'description': '',
                'cultural': 0,
                'political': 0,
                'sports': 0,
                'religious': 1,
                'health': 0,
                'celebrity': 0,
                'international': 0
            })

        return articles

    # ── Description Fetcher ──────────────────────────────────────────────────
    def fetch_description(self, art):
        if art.get('description') and len(art['description']) > 50:
            return art
        try:
            r = self.get(art['url'], timeout=10)
            if not r:
                return art
            soup = BeautifulSoup(r.content, 'html.parser')

            for sel in ['div.details-content','div.story-content','div.article-content',
                       'div.details-body','div.news-content','div.post-content',
                       'div.entry-content','div.details','article',
                       'div[itemprop="articleBody"]','div.content-details']:
                body = soup.select_one(sel)
                if body:
                    paras = [p.get_text(strip=True) for p in body.find_all('p')
                            if len(p.get_text(strip=True)) > 20]
                    text = ' '.join(paras[:6])
                    if len(text) > 80:
                        art['description'] = text[:600]+('...' if len(text)>600 else '')
                        return art

            # Fallback
            paras = [p.get_text(strip=True) for p in soup.find_all('p')
                    if len(p.get_text(strip=True)) > 20]
            text = ' '.join(paras[:6])
            if text:
                art['description'] = text[:600]+('...' if len(text)>600 else '')
        except:
            pass
        return art

    def fetch_descriptions_parallel(self, articles):
        need = [a for a in articles if not a.get('description') or len(a['description']) < 50]
        ready = [a for a in articles if a.get('description') and len(a['description']) >= 50]

        if not need:
            print(f"  All {len(ready)} descriptions from RSS ✓")
            return articles

        print(f"  Fetching {len(need)} descriptions ({len(ready)} from RSS)...")
        results = list(ready)
        done = 0

        with ThreadPoolExecutor(max_workers=THREADS) as ex:
            futures = {ex.submit(self.fetch_description, a): a for a in need}
            for f in as_completed(futures):
                results.append(f.result())
                done += 1
                if done % 30 == 0 or done == len(need):
                    print(f"  → {done}/{len(need)} fetched")

        return results

    # ── Main Collection ──────────────────────────────────────────────────────
    def collect_religious_news(self, target=TARGET_ARTICLES):
        print("="*70)
        print("RELIGIOUS NEWS SCRAPER")
        print("="*70)
        print(f"Target: {target} articles")
        print(f"Sources: {len(RELIGIOUS_SOURCES)} (RSS + HTML)")
        print("="*70)

        collected = []

        for src_type, url_tmpl, src_name in RELIGIOUS_SOURCES:
            if len(collected) >= target:
                break

            if src_type == 'rss':
                print(f"\nRSS  [{src_name:20s}]", end=" ")
                arts = self.scrape_rss(url_tmpl, src_name)
                collected.extend(arts)
                print(f"✓ {len(arts):3d} articles  | Total: {len(collected)}/{target}")
                time.sleep(1)

            elif src_type == 'html':
                print(f"\nHTML [{src_name:20s}]")
                for page in range(1, MAX_PAGES + 1):
                    if len(collected) >= target:
                        break

                    url = url_tmpl.replace('{page}', str(page))
                    arts = self.scrape_html(url, src_name)

                    if not arts:
                        print(f"  Page {page:02d}: No articles, stopping pagination")
                        break

                    collected.extend(arts)
                    print(f"  Page {page:02d}: +{len(arts):3d} articles  | Total: {len(collected)}/{target}")
                    time.sleep(1)

        print(f"\n{'='*70}")
        print(f"RAW COLLECTION: {len(collected)} articles")
        print(f"{'='*70}")

        # Fetch descriptions
        if collected:
            print("\nFetching article descriptions...")
            collected = self.fetch_descriptions_parallel(collected)

        return collected

    # ── Save CSV ─────────────────────────────────────────────────────────────
    def save_csv(self, articles):
        df = pd.DataFrame(articles)

        cols = ['text', 'date', 'cultural', 'political', 'sports',
                'religious', 'health', 'celebrity', 'international',
                'label', 'description', 'source', 'verdict', 'url']

        for col in cols:
            if col not in df.columns:
                df[col] = '' if col in ['description','url','text','source','verdict'] else 0

        df = df[cols]
        df.insert(0, 'Column1', range(1, len(df)+1))
        df.to_csv(OUTPUT_FILE, index=False, encoding='utf-8-sig')

        total = len(df)
        desc_ok = (df['description'].str.len() > 0).sum()
        avg_len = df[df['description'].str.len()>0]['description'].str.len().mean() if desc_ok > 0 else 0

        print(f"\n{'='*70}")
        print(f"SAVED TO CSV")
        print(f"{'='*70}")
        print(f"Filename: {OUTPUT_FILE}")
        print(f"Total articles: {total}")

        print(f"\nData quality:")
        print(f"  URLs filled: {df['url'].notna().sum()}/{total}")
        print(f"  Descriptions filled: {desc_ok}/{total} ({desc_ok/total*100:.1f}%)")
        print(f"  Avg description length: {avg_len:.0f} chars")

        print(f"\nCategory check:")
        print(f"  Religious: {df['religious'].sum()} (should be {total})")

        print(f"\nSource distribution:")
        print(df['source'].value_counts())

        return df

    # ── Run ──────────────────────────────────────────────────────────────────
    def run(self):
        articles = self.collect_religious_news(target=TARGET_ARTICLES)
        df = self.save_csv(articles)

        print(f"\n{'='*70}")
        print(f"✓ COMPLETE!")
        print(f"{'='*70}")
        print(f"Got {len(df)} religious news articles")
        print(f"Target was: {TARGET_ARTICLES}")
        print(f"Achievement: {len(df)/TARGET_ARTICLES*100:.1f}%")

        if len(df) >= 180:
            print(f"\n✓ SUCCESS! Ready to merge with your main dataset")
        else:
            print(f"\n⚠️  Got {len(df)} articles (target was 180-200)")

        return df


# ══════════════════════════════════════════════════════════════════════════════
if __name__ == '__main__':
    scraper = ReligiousNewsScraper()
    df = scraper.run()

import pandas as pd

# Load both datasets
print("Loading datasets...")
main_df = pd.read_csv('manoshi_non rumour dataset.csv')
religious_df = pd.read_csv('religious_news_dataset.csv')

print(f"Main dataset: {len(main_df)} articles")
print(f"Religious dataset: {len(religious_df)} articles")

# Combine them
print("\nMerging datasets...")
combined = pd.concat([main_df, religious_df], ignore_index=True)

print(f"Combined (before dedup): {len(combined)} articles")

# Remove duplicates based on article text
combined = combined.drop_duplicates(subset=['text'], keep='first')

print(f"Combined (after dedup): {len(combined)} articles")

# Reset the Column1 index
combined['Column1'] = range(1, len(combined) + 1)

# Save final merged dataset
combined.to_csv('real_news_complete_dataset.csv', index=False, encoding='utf-8-sig')

print(f"\n{'='*70}")
print(f"✓ MERGE COMPLETE!")
print(f"{'='*70}")
print(f"Final dataset: real_news_complete_dataset.csv")
print(f"Total articles: {len(combined)}")

# Show category distribution
print(f"\nCategory distribution:")
for col in ['cultural', 'political', 'sports', 'religious', 'health', 'celebrity', 'international']:
    count = combined[col].sum()
    pct = count / len(combined) * 100
    print(f"  {col:15s}: {count:>4} ({pct:>5.1f}%)")

# Show source distribution
print(f"\nTop 10 sources:")
print(combined['source'].value_counts().head(10))

print(f"\n✓ Ready to combine with your 900 rumor dataset!")
print(f"  Total: {len(combined)} real + 900 rumors = {len(combined) + 900} total dataset")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (classification_report, confusion_matrix,
                              accuracy_score, f1_score, roc_auc_score,
                              precision_score, recall_score)
from scipy.sparse import hstack, csr_matrix
import xgboost as xgb

# ══════════════════════════════════════════════════════════════════════════════
# 1. LOAD DATA
# ══════════════════════════════════════════════════════════════════════════════

def load_data(rumour_path, non_rumour_path):
    """
    Load both datasets and combine.
    Expected columns: 'text', 'description', and category columns
    """
    # Use pd.read_excel for .xlsx files and pd.read_csv for .csv files
    if rumour_path.endswith('.xlsx'):
        df_rumour = pd.read_excel(rumour_path)
    else:
        df_rumour = pd.read_csv(rumour_path, encoding='utf-8-sig')

    if non_rumour_path.endswith('.xlsx'):
        df_non_rumour = pd.read_excel(non_rumour_path)
    else:
        df_non_rumour = pd.read_csv(non_rumour_path, encoding='utf-8-sig')

    # Assign labels
    df_rumour['label']     = 1   # rumour
    df_non_rumour['label'] = 0   # non-rumour

    df = pd.concat([df_rumour, df_non_rumour], ignore_index=True)

    # Combine title + description into one text field for richer features
    df['full_text'] = df['text'].fillna('') + ' ' + df['description'].fillna('')
    df['full_text'] = df['full_text'].str.strip()

    # Drop rows with empty text
    df = df[df['full_text'].str.len() > 10].reset_index(drop=True)

    print(f"Dataset loaded:")
    print(f"  Total   : {len(df)}")
    print(f"  Rumour  : {df['label'].sum()}")
    print(f"  Non-rum : {(df['label']==0).sum()}")
    return df


# ══════════════════════════════════════════════════════════════════════════════
# 2. LINGUISTIC MARKER EXTRACTION
# ══════════════════════════════════════════════════════════════════════════════

class BengaliLinguisticMarkers:
    """
    Extract features that linguistically differentiate rumors from non-rumors.
    All features are interpretable — useful for analysis + publication.
    """

    # ── Rumour-leaning word lists ────────────────────────────────────────────
    UNCERTAINTY_WORDS = [
        'সম্ভবত', 'হয়তো', 'মনে হয়', 'শোনা যাচ্ছে', 'নাকি', 'বলা হচ্ছে',
        'জানা গেছে', 'খবর', 'দাবি', 'অভিযোগ', 'আশঙ্কা', 'সন্দেহ',
        'মনে করা হচ্ছে', 'ধারণা করা হচ্ছে', 'বলে মনে করা'
    ]

    SENSATIONAL_WORDS = [
        'ভয়াবহ', 'আতঙ্ক', 'বিপদ', 'শক', 'চাঞ্চল্যকর', 'বিস্ফোরণ',
        'ভাইরাল', 'হইচই', 'তোলপাড়', 'রহস্য', 'অবিশ্বাস্য', 'হতবাক',
        'থ্রিলার', 'নাটকীয়', 'ভয়', 'আতঙ্কিত', 'আলোড়ন'
    ]

    URGENCY_WORDS = [
        'এখনই', 'তাড়াতাড়ি', 'দ্রুত', 'সতর্ক', 'সাবধান', 'শেয়ার করুন',
        'ছড়িয়ে দিন', 'জরুরি', 'বিপদ সংকেত', 'সাবধানতা'
    ]

    VAGUE_SOURCE_WORDS = [
        'একটি সূত্র', 'নাম প্রকাশে অনিচ্ছুক', 'জানা গেছে',
        'বিভিন্ন সূত্রে', 'সোশ্যাল মিডিয়া', 'ফেসবুকে', 'হোয়াটসঅ্যাপে',
        'ইন্টারনেটে', 'অনলাইনে ছড়িয়ে'
    ]

    # ── Real-news leaning word lists ─────────────────────────────────────────
    CREDIBLE_SOURCE_WORDS = [
        'মন্ত্রণালয়', 'সরকারি', 'আনুষ্ঠানিক', 'বিবৃতি', 'সংবাদ সম্মেলন',
        'মুখপাত্র', 'কর্মকর্তা', 'প্রতিনিধি', 'নিশ্চিত করেছেন', 'জানিয়েছেন'
    ]

    NEGATION_WORDS = [
        'না', 'নয়', 'নেই', 'ছিল না', 'হয়নি', 'করেনি', 'পারেনি',
        'মিথ্যা', 'ভুল', 'গুজব', 'সত্য নয়'
    ]

    def extract(self, text):
        """Extract all linguistic markers from a single text. Returns dict."""
        if not isinstance(text, str):
            text = ''

        features = {}

        # ── Basic surface features ───────────────────────────────────────────
        features['char_count']      = len(text)
        features['word_count']      = len(text.split())
        features['sentence_count']  = max(1, len(re.split(r'[।!?]', text)))
        features['avg_word_length'] = np.mean([len(w) for w in text.split()]) if text.split() else 0
        features['avg_sent_length'] = features['word_count'] / features['sentence_count']

        # ── Punctuation features ─────────────────────────────────────────────
        features['exclamation_count'] = text.count('!')
        features['question_count']    = text.count('?')
        features['ellipsis_count']    = text.count('...') + text.count('…')
        features['quote_count']       = text.count('"') + text.count("' ") + text.count('"') + text.count('"')
        features['has_caps_bengali']  = int(bool(re.search(r'[A-Z]{2,}', text)))  # English caps in Bengali text

        # ── Lexical diversity (Type-Token Ratio) ─────────────────────────────
        words = text.split()
        features['ttr'] = len(set(words)) / len(words) if words else 0

        # ── Repetition (low TTR = high repetition, common in rumors) ─────────
        features['repetition_rate'] = 1 - features['ttr']

        # ── Linguistic marker counts ──────────────────────────────────────────
        features['uncertainty_count']    = sum(1 for w in self.UNCERTAINTY_WORDS    if w in text)
        features['sensational_count']    = sum(1 for w in self.SENSATIONAL_WORDS    if w in text)
        features['urgency_count']        = sum(1 for w in self.URGENCY_WORDS        if w in text)
        features['vague_source_count']   = sum(1 for w in self.VAGUE_SOURCE_WORDS   if w in text)
        features['credible_source_count']= sum(1 for w in self.CREDIBLE_SOURCE_WORDS if w in text)
        features['negation_count']       = sum(1 for w in self.NEGATION_WORDS       if w in text)

        # ── Derived ratios ────────────────────────────────────────────────────
        wc = max(1, features['word_count'])
        features['uncertainty_ratio']    = features['uncertainty_count']     / wc
        features['sensational_ratio']    = features['sensational_count']    / wc
        features['urgency_ratio']        = features['urgency_count']        / wc
        features['vague_source_ratio']   = features['vague_source_count']   / wc
        features['credible_source_ratio']= features['credible_source_count']/ wc

        # ── Rumour score (composite) — higher = more rumour-like ─────────────
        features['rumour_score'] = (
            features['uncertainty_count'] * 2 +
            features['sensational_count'] * 2 +
            features['urgency_count']     * 3 +
            features['vague_source_count']* 2 -
            features['credible_source_count'] * 2
        )

        # ── Number presence (real news has more specific numbers) ─────────────
        numbers = re.findall(r'\d+', text)
        features['number_count']     = len(numbers)
        features['has_percentage']   = int('%' in text or 'শতাংশ' in text or 'ভাগ' in text)
        features['has_large_number'] = int(any(int(n) > 10000 for n in numbers if n.isdigit() and len(n)<=10))

        # ── URL / link presence (rumors often reference social media) ─────────
        features['has_url']      = int(bool(re.search(r'http|www\.', text)))
        features['has_facebook'] = int('ফেসবুক' in text or 'facebook' in text.lower())

        return features

    def extract_all(self, texts):
        """Extract features for all texts. Returns DataFrame."""
        print(f"  Extracting linguistic markers from {len(texts)} texts...", flush=True)
        records = [self.extract(t) for t in texts]
        df_feat = pd.DataFrame(records)
        print(f"  ✓ {len(df_feat.columns)} features extracted per text")
        return df_feat


# ══════════════════════════════════════════════════════════════════════════════
# 3. ANALYSIS — What markers differ between rumours and non-rumours?
# ══════════════════════════════════════════════════════════════════════════════

def analyze_markers(df_features, labels, top_n=15):
    """Statistical comparison of each marker between rumour / non-rumour."""
    from scipy import stats

    df = df_features.copy()
    df['label'] = labels

    rumour_df     = df[df['label'] == 1]
    non_rumour_df = df[df['label'] == 0]

    results = []
    for col in df_features.columns:
        r_mean = rumour_df[col].mean()
        n_mean = non_rumour_df[col].mean()
        t_stat, p_val = stats.ttest_ind(rumour_df[col], non_rumour_df[col])
        results.append({
            'feature':        col,
            'rumour_mean':    round(r_mean, 4),
            'non_rumour_mean':round(n_mean, 4),
            'difference':     round(r_mean - n_mean, 4),
            't_statistic':    round(t_stat, 4),
            'p_value':        round(p_val, 6),
            'significant':    p_val < 0.05
        })

    results_df = pd.DataFrame(results).sort_values('p_value')
    print("\nTop statistically significant markers:")
    print(results_df[results_df['significant']].head(top_n).to_string(index=False))

    # Save analysis
    results_df.to_csv('linguistic_marker_analysis.csv', index=False)
    print("\n✓ Saved: linguistic_marker_analysis.csv")
    return results_df


# ══════════════════════════════════════════════════════════════════════════════
# 4. VISUALIZATION
# ══════════════════════════════════════════════════════════════════════════════

def plot_marker_comparison(df_features, labels, save_path='marker_comparison.png'):
    """Bar chart comparing key markers between rumour and non-rumour."""
    key_markers = [
        'uncertainty_count', 'sensational_count', 'urgency_count',
        'vague_source_count', 'credible_source_count', 'question_count',
        'exclamation_count', 'ttr', 'avg_sent_length', 'number_count'
    ]
    key_markers = [m for m in key_markers if m in df_features.columns]

    df = df_features[key_markers].copy()
    df['label'] = labels

    rumour_means     = df[df['label']==1][key_markers].mean()
    non_rumour_means = df[df['label']==0][key_markers].mean()

    x = np.arange(len(key_markers))
    width = 0.35

    fig, ax = plt.subplots(figsize=(14, 6))
    bars1 = ax.bar(x - width/2, rumour_means,     width, label='Rumour',     color='#e74c3c', alpha=0.85)
    bars2 = ax.bar(x + width/2, non_rumour_means, width, label='Non-Rumour', color='#2ecc71', alpha=0.85)

    ax.set_xlabel('Linguistic Markers', fontsize=12)
    ax.set_ylabel('Mean Value', fontsize=12)
    ax.set_title('Linguistic Marker Comparison: Rumour vs Non-Rumour (Bengali)', fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(key_markers, rotation=45, ha='right', fontsize=9)
    ax.legend(fontsize=11)
    ax.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.show()
    print(f"✓ Saved: {save_path}")


def plot_confusion_matrix(cm, model_name, save_path=None):
    fig, ax = plt.subplots(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Non-Rumour','Rumour'],
                yticklabels=['Non-Rumour','Rumour'], ax=ax)
    ax.set_title(f'Confusion Matrix — {model_name}', fontweight='bold')
    ax.set_ylabel('True Label')
    ax.set_xlabel('Predicted Label')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=120)
    plt.show()


def plot_model_comparison(results_df, save_path='model_comparison.png'):
    """Bar chart of all 9 models by F1 score."""
    fig, ax = plt.subplots(figsize=(12, 5))
    colors = ['#3498db' if f < results_df['F1'].max() else '#e74c3c'
              for f in results_df['F1']]
    bars = ax.bar(results_df['Model'], results_df['F1'], color=colors, alpha=0.85, edgecolor='white')

    for bar, val in zip(bars, results_df['F1']):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{val:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

    ax.set_ylim(0, 1.05)
    ax.set_ylabel('F1 Score (Macro)', fontsize=12)
    ax.set_title('Model Comparison — Bengali Rumour Detection', fontsize=14, fontweight='bold')
    ax.set_xticklabels(results_df['Model'], rotation=30, ha='right', fontsize=9)
    ax.grid(axis='y', alpha=0.3)
    ax.axhline(y=results_df['F1'].mean(), color='gray', linestyle='--', alpha=0.6, label=f"Mean F1 = {results_df['F1'].mean():.3f}")
    ax.legend()
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.show()
    print(f"✓ Saved: {save_path}")


# ══════════════════════════════════════════════════════════════════════════════
# 5. MODEL TRAINING
# ══════════════════════════════════════════════════════════════════════════════

class RumourDetectionPipeline:

    def __init__(self):
        self.scaler      = StandardScaler()
        self.tfidf       = TfidfVectorizer(max_features=10000, ngram_range=(1,2),
                                           analyzer='char_wb', min_df=2)
        # char-level TF-IDF works better for Bengali morphology
        self.results     = []
        self.marker_extractor = BengaliLinguisticMarkers()

    def prepare_features(self, df, fit=True):
        """Prepare combined feature matrix: TF-IDF + linguistic markers."""
        texts = df['full_text'].fillna('').tolist()

        # TF-IDF
        if fit:
            tfidf_matrix = self.tfidf.fit_transform(texts)
        else:
            tfidf_matrix = self.tfidf.transform(texts)

        # Linguistic markers
        df_markers = self.marker_extractor.extract_all(texts)
        if fit:
            marker_matrix = self.scaler.fit_transform(df_markers)
        else:
            marker_matrix = self.scaler.transform(df_markers)

        return tfidf_matrix, marker_matrix, df_markers

    def evaluate(self, model_name, y_true, y_pred, y_prob=None):
        """Compute and store all metrics."""
        acc  = accuracy_score(y_true, y_pred)
        prec = precision_score(y_true, y_pred, average='macro', zero_division=0)
        rec  = recall_score(y_true, y_pred, average='macro', zero_division=0)
        f1   = f1_score(y_true, y_pred, average='macro', zero_division=0)
        auc  = roc_auc_score(y_true, y_prob) if y_prob is not None else 0.0
        cm   = confusion_matrix(y_true, y_pred)

        print(f"\n  {'─'*50}")
        print(f"  Model    : {model_name}")
        print(f"  Accuracy : {acc:.4f}")
        print(f"  F1 Macro : {f1:.4f}")
        print(f"  Precision: {prec:.4f}")
        print(f"  Recall   : {rec:.4f}")
        if y_prob is not None:
            print(f"  ROC-AUC  : {auc:.4f}")
        print(f"\n{classification_report(y_true, y_pred, target_names=['Non-Rumour','Rumour'])}")

        plot_confusion_matrix(cm, model_name,
                              save_path=f"cm_{model_name.replace(' ','_')}.png")

        self.results.append({
            'Model': model_name, 'Accuracy': round(acc,4),
            'Precision': round(prec,4), 'Recall': round(rec,4),
            'F1': round(f1,4), 'AUC': round(auc,4)
        })
        return f1

    # ── MODELS 1–5: Traditional ML ───────────────────────────────────────────

    def train_model1_logreg(self, X_tfidf_train, X_tfidf_test, y_train, y_test):
        print("\n▶ Model 1: Logistic Regression (TF-IDF)")
        clf = LogisticRegression(max_iter=1000, C=1.0, class_weight='balanced')
        clf.fit(X_tfidf_train, y_train)
        y_pred = clf.predict(X_tfidf_test)
        y_prob = clf.predict_proba(X_tfidf_test)[:,1]
        self.evaluate("Logistic Regression", y_test, y_pred, y_prob)
        return clf

    def train_model2_nb(self, X_tfidf_train, X_tfidf_test, y_train, y_test):
        print("\n▶ Model 2: Multinomial Naive Bayes (TF-IDF)")
        from sklearn.preprocessing import MaxAbsScaler
        scaler = MaxAbsScaler()
        X_tr = scaler.fit_transform(X_tfidf_train)
        X_te = scaler.transform(X_tfidf_test)
        clf = MultinomialNB(alpha=0.1)
        clf.fit(abs(X_tr), y_train)
        y_pred = clf.predict(abs(X_te))
        y_prob = clf.predict_proba(abs(X_te))[:,1]
        self.evaluate("Naive Bayes", y_test, y_pred, y_prob)
        return clf

    def train_model3_svm(self, X_tfidf_train, X_tfidf_test, y_train, y_test):
        print("\n▶ Model 3: SVM (TF-IDF)")
        clf = SVC(kernel='linear', probability=True, class_weight='balanced', C=1.0)
        clf.fit(X_tfidf_train, y_train)
        y_pred = clf.predict(X_tfidf_test)
        y_prob = clf.predict_proba(X_tfidf_test)[:,1]
        self.evaluate("SVM", y_test, y_pred, y_prob)
        return clf

    def train_model4_rf(self, X_marker_train, X_marker_test, y_train, y_test):
        print("\n▶ Model 4: Random Forest (Linguistic Markers only)")
        clf = RandomForestClassifier(n_estimators=200, max_depth=10,
                                     class_weight='balanced', random_state=42)
        clf.fit(X_marker_train, y_train)
        y_pred = clf.predict(X_marker_test)
        y_prob = clf.predict_proba(X_marker_test)[:,1]
        self.evaluate("Random Forest", y_test, y_pred, y_prob)
        return clf

    def train_model5_xgb(self, X_marker_train, X_marker_test, y_train, y_test):
        print("\n▶ Model 5: XGBoost (Linguistic Markers only)")
        scale_pos = (y_train==0).sum() / (y_train==1).sum()
        clf = xgb.XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.1,
                                 scale_pos_weight=scale_pos, use_label_encoder=False,
                                 eval_metric='logloss', random_state=42)
        clf.fit(X_marker_train, y_train)
        y_pred = clf.predict(X_marker_test)
        y_prob = clf.predict_proba(X_marker_test)[:,1]
        self.evaluate("XGBoost", y_test, y_pred, y_prob)
        return clf

    def train_model6_combined_rf(self, X_tfidf_train, X_tfidf_test,
                                  X_marker_train, X_marker_test, y_train, y_test):
        print("\n▶ Model 6: Random Forest (TF-IDF + Linguistic Markers combined)")
        X_train_comb = np.hstack([X_tfidf_train.toarray(), X_marker_train])
        X_test_comb  = np.hstack([X_tfidf_test.toarray(),  X_marker_test])
        clf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42)
        clf.fit(X_train_comb, y_train)
        y_pred = clf.predict(X_test_comb)
        y_prob = clf.predict_proba(X_test_comb)[:,1]
        self.evaluate("RF (TF-IDF + Markers)", y_test, y_pred, y_prob)
        return clf

    def train_model7_combined_xgb(self, X_tfidf_train, X_tfidf_test,
                                   X_marker_train, X_marker_test, y_train, y_test):
        print("\n▶ Model 7: XGBoost (TF-IDF + Linguistic Markers combined)")
        X_train_comb = np.hstack([X_tfidf_train.toarray(), X_marker_train])
        X_test_comb  = np.hstack([X_tfidf_test.toarray(),  X_marker_test])
        clf = xgb.XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.1,
                                 use_label_encoder=False, eval_metric='logloss', random_state=42)
        clf.fit(X_train_comb, y_train)
        y_pred = clf.predict(X_test_comb)
        y_prob = clf.predict_proba(X_test_comb)[:,1]
        self.evaluate("XGBoost (TF-IDF + Markers)", y_test, y_pred, y_prob)
        return clf

    # ── MODELS 8–9: Deep Learning (BanglaBERT / mBERT) ───────────────────────

    def train_model8_mbert(self, df_train, df_test):
        print("\n▶ Model 8: mBERT Fine-tuned")
        try:
            from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                                      Trainer, TrainingArguments)
            import torch
            from torch.utils.data import Dataset

            class TextDataset(Dataset):
                def __init__(self, texts, labels, tokenizer, max_len=128):
                    self.encodings = tokenizer(texts, truncation=True, padding=True,
                                               max_length=max_len, return_tensors='pt')
                    self.labels = torch.tensor(labels, dtype=torch.long)
                def __len__(self): return len(self.labels)
                def __getitem__(self, i):
                    item = {key: val[i] for key, val in self.encodings.items()}
                    item['labels'] = self.labels[i]
                    return item

            MODEL_NAME = 'bert-base-multilingual-cased'
            tokenizer  = AutoTokenizer.from_pretrained(MODEL_NAME)
            model      = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

            train_texts  = df_train['full_text'].tolist()
            test_texts   = df_test['full_text'].tolist()
            train_labels = df_train['label'].tolist()
            test_labels  = df_test['label'].tolist()

            train_dataset = TextDataset(train_texts, train_labels, tokenizer)
            test_dataset  = TextDataset(test_texts,  test_labels,  tokenizer)

            args = TrainingArguments(
                output_dir='./mbert_output', num_train_epochs=3,
                per_device_train_batch_size=16, per_device_eval_batch_size=32,
                eval_strategy='epoch', save_strategy='epoch',
                load_best_model_at_end=True, logging_steps=50,
                warmup_steps=100, weight_decay=0.01,
            )

            trainer = Trainer(model=model, args=args,
                              train_dataset=train_dataset,
                              eval_dataset=test_dataset)
            trainer.train()

            preds_out = trainer.predict(test_dataset)
            y_pred    = np.argmax(preds_out.predictions, axis=1)
            y_prob    = torch.softmax(torch.tensor(preds_out.predictions), dim=1)[:,1].numpy()
            self.evaluate("mBERT", test_labels, y_pred, y_prob)

        except ImportError:
            print("  ⚠ transformers/torch not installed. Skipping mBERT.")
            print("    Install: !pip install transformers torch -q")

    def train_model9_banglabert(self, df_train, df_test):
        print("\n▶ Model 9: BanglaBERT Fine-tuned (BEST MODEL)")
        try:
            from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                                      Trainer, TrainingArguments)
            import torch
            from torch.utils.data import Dataset

            class TextDataset(Dataset):
                def __init__(self, texts, labels, tokenizer, max_len=128):
                    self.encodings = tokenizer(texts, truncation=True, padding=True,
                                               max_length=max_len, return_tensors='pt')
                    self.labels = torch.tensor(labels, dtype=torch.long)
                def __len__(self): return len(self.labels)
                def __getitem__(self, i):
                    item = {key: val[i] for key, val in self.encodings.items()}
                    item['labels'] = self.labels[i]
                    return item

            # BanglaBERT — trained specifically on Bengali text
            MODEL_NAME = 'sagorsarker/bangla-bert-base'
            tokenizer  = AutoTokenizer.from_pretrained(MODEL_NAME)
            model      = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

            train_texts  = df_train['full_text'].tolist()
            test_texts   = df_test['full_text'].tolist()
            train_labels = df_train['label'].tolist()
            test_labels  = df_test['label'].tolist()

            train_dataset = TextDataset(train_texts, train_labels, tokenizer)
            test_dataset  = TextDataset(test_texts,  test_labels,  tokenizer)

            args = TrainingArguments(
                output_dir='./banglabert_output', num_train_epochs=4,
                per_device_train_batch_size=16, per_device_eval_batch_size=32,
                eval_strategy='epoch', save_strategy='epoch',
                load_best_model_at_end=True, logging_steps=50,
                warmup_steps=200, weight_decay=0.01, learning_rate=2e-5,
            )

            trainer = Trainer(model=model, args=args,
                              train_dataset=train_dataset,
                              eval_dataset=test_dataset)
            trainer.train()

            preds_out = trainer.predict(test_dataset)
            y_pred    = np.argmax(preds_out.predictions, axis=1)
            y_prob    = torch.softmax(torch.tensor(preds_out.predictions), dim=1)[:,1].numpy()
            self.evaluate("BanglaBERT", test_labels, y_pred, y_prob)

        except ImportError:
            print("  ⚠ transformers/torch not installed. Skipping BanglaBERT.")
            print("    Install: !pip install transformers torch -q")

    # ── Feature importance plot ───────────────────────────────────────────────

    def plot_feature_importance(self, clf, feature_names, model_name, top_n=20):
        if not hasattr(clf, 'feature_importances_'):
            return
        importances = clf.feature_importances_
        idx = np.argsort(importances)[-top_n:]
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.barh([feature_names[i] for i in idx], importances[idx], color='#3498db', alpha=0.85)
        ax.set_title(f'Top {top_n} Feature Importances — {model_name}', fontweight='bold')
        ax.set_xlabel('Importance')
        plt.tight_layout()
        plt.savefig(f'feature_importance_{model_name.replace(" ","_")}.png', dpi=120)
        plt.show()

    # ── Run full pipeline ─────────────────────────────────────────────────────

    def run(self, df):
        print("═"*70)
        print("  BENGALI RUMOUR DETECTION — FULL PIPELINE")
        print("═"*70)

        # ── Train/test split ─────────────────────────────────────────────────
        df_train, df_test = train_test_split(
            df, test_size=0.2, random_state=42, stratify=df['label']
        )
        print(f"\n  Train: {len(df_train)}  |  Test: {len(df_test)}")
        print(f"  Train label dist: {df_train['label'].value_counts().to_dict()}")
        print(f"  Test  label dist: {df_test['label'].value_counts().to_dict()}")

        # ── Feature extraction ───────────────────────────────────────────────
        print("\n  Preparing features...")
        X_tfidf_train, X_marker_train, _ = self.prepare_features(df_train, fit=True)
        X_tfidf_test,  X_marker_test,  _ = self.prepare_features(df_test,  fit=False)

        y_train = df_train['label'].values
        y_test  = df_test['label'].values

        # ── Linguistic marker analysis ────────────────────────────────────────
        print("\n  Running marker analysis...")
        _, _, train_markers = self.prepare_features(df_train, fit=False)
        marker_analysis = analyze_markers(train_markers, y_train)
        plot_marker_comparison(train_markers, y_train)

        # ── Train all 9 models ────────────────────────────────────────────────
        print("\n" + "═"*70)
        print("  TRAINING 9 MODELS")
        print("═"*70)

        self.train_model1_logreg(X_tfidf_train, X_tfidf_test, y_train, y_test)
        self.train_model2_nb(X_tfidf_train, X_tfidf_test, y_train, y_test)
        self.train_model3_svm(X_tfidf_train, X_tfidf_test, y_train, y_test)
        self.train_model4_rf(X_marker_train, X_marker_test, y_train, y_test)
        self.train_model5_xgb(X_marker_train, X_marker_test, y_train, y_test)
        self.train_model6_combined_rf(X_tfidf_train, X_tfidf_test,
                                      X_marker_train, X_marker_test, y_train, y_test)
        self.train_model7_combined_xgb(X_tfidf_train, X_tfidf_test,
                                       X_marker_train, X_marker_test, y_train, y_test)
        self.train_model8_mbert(df_train, df_test)
        self.train_model9_banglabert(df_train, df_test)

        # ── Final comparison table ────────────────────────────────────────────
        results_df = pd.DataFrame(self.results).sort_values('F1', ascending=False)
        print("\n" + "═"*70)
        print("  FINAL RESULTS — ALL 9 MODELS")
        print("═"*70)
        print(results_df.to_string(index=False))

        results_df.to_csv('model_results.csv', index=False)
        plot_model_comparison(results_df)

        print("\n✓ All outputs saved:")
        print("  model_results.csv")
        print("  linguistic_marker_analysis.csv")
        print("  marker_comparison.png")
        print("  model_comparison.png")
        print("  cm_*.png  (confusion matrix per model)")
        return results_df


# ══════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════
if __name__ == '__main__':

    # ── STEP 1: Load your datasets ────────────────────────────────────────────
    # Update these paths to your actual files
    RUMOUR_PATH     = '/content/rumourdataset.csv'       # your 900 rumour rows
    NON_RUMOUR_PATH = '/content/nonrumourdataset.csv'    # your 900 real news rows

    df = load_data(RUMOUR_PATH, NON_RUMOUR_PATH)

    # ── STEP 2: Run full pipeline ─────────────────────────────────────────────
    pipeline = RumourDetectionPipeline()
    results  = pipeline.run(df)